name: CI

on:
  workflow_dispatch:
  # pull_request:
  #   branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Parse Azure Credentials
      run: |
        echo "AZURE_AD_APPLICATION_ID=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.appId')" >> $GITHUB_ENV
        echo "AZURE_AD_SP_PASSWORD=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.password')" >> $GITHUB_ENV

    - name: Set environment name
      id: env_setup
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "env_name=dev" >> $GITHUB_OUTPUT
        fi

    - name: Build Docker image
      run: docker build . -t cloud_engineer:${{ github.sha }}--${{ steps.env_setup.outputs.env_name }}-test

    - name: Run tests in Docker container
      run: docker run cloud_engineer:${{ github.sha }}--${{ steps.env_setup.outputs.env_name }}-test npm test

    - name: Log in to the Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_NAME }}.azurecr.io
        username: ${{ secrets.AZURE_AD_APPLICATION_ID }}
        password: ${{ secrets.AZURE_AD_SP_PASSWORD }}

    - name: Check if ACR exists
      id: acr_check
      run: |
        exists=$(az acr show --name ${{ secrets.ACR_NAME }} --query "name" -o tsv)
        echo "ACR_EXISTS=$exists" >> $GITHUB_ENV

    - name: Tag and push Docker image to ACR (Conditional)
      if: env.ACR_EXISTS != ''
      run: |
        docker tag cloud_engineer:${{ github.sha }}--${{ steps.env_setup.outputs.env_name }}-test ${{ secrets.ACR_NAME }}.azurecr.io/cloud_engineer:${{ github.sha }}--${{ steps.env_setup.outputs.env_name }}
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/cloud_engineer:${{ github.sha }}--${{ steps.env_setup.outputs.env_name }}