name: ID

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  initial-deploy:
    runs-on: ubuntu-latest
    
    env:
      TF_VERSION: '1.7.4'
      TF_WORKING_DIR: './terraform'
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}    
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Validate
        run: terraform validate -no-color
      
      - name: Tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          tfsec_args: --soft-fail
          github_token: ${{ github.token }}
      
      - name: Terraform Plan 
        run: terraform plan -no-color -input=false -out=tf.plan -var-file="terraform.tfvars.dev"
        continue-on-error: true
        working-directory: ${{ env.TF_WORKING_DIR }}
      
      - name: Terraform Apply
        env:
          GH_TOKEN: ${{ github.token }}
        run: terraform apply -auto-approve tf.plan
        working-directory: ${{ env.TF_WORKING_DIR }}